version: '2'

services:
   database:
     image: mysql:5.7
     restart: always
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: foodie
       MYSQL_USER: foodie
       MYSQL_PASSWORD: foodie
